{{- if .Values.global.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    k8s-app: heptio-ark
  name: ark
subjects:
  - kind: ServiceAccount
    namespace: {{ .Values.ark.server.namespace }}
    name: ark
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{- end }}
