apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: ark-deployment
  namespace: {{ .Values.ark.server.namespace }}
data:
  config.yaml: |-
    apiVersion: ark.heptio.com/v1
    kind: Config
    metadata:
      labels:
        chart: {{ .Chart.Name }}
        component: {{ template "fullname" . }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        k8s-app: heptio-ark
      name: default
      namespace: {{ .Values.ark.namespace }}
    persistentVolumeProvider:
      name: aws
      config:
        region: {{ .Values.ark.configuration.region }}
    backupStorageProvider:
      name: aws
      bucket: {{ .Values.ark.configuration.bucket }}
      config:
        region: {{ .Values.ark.configuration.region }}
    backupSyncPeriod: 30m
    gcSyncPeriod: 30m
    scheduleSyncPeriod: 1m
    restoreOnlyMode: false
  ark.yaml: |-
    apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      labels:
        chart: {{ .Chart.Name }}
        component: {{ template "fullname" . }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        k8s-app: heptio-ark
      name: ark
      namespace: {{ .Values.ark.server.namespace }}
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            component: {{ template "fullname" . }}
        spec:
          restartPolicy: Always
          serviceAccountName: ark
          containers:
            - name: ark
              image: {{ .Values.ark.image.name }}:{{ .Values.ark.image.tag }}
              command:
                - /ark
              args:
                - server
                - --namespace
                - {{ .Values.ark.namespace }}
              volumeMounts:
                - name: plugins
                  mountPath: /plugins
          volumes:
            - name: plugins
              emptyDir: {}
