apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "3"
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: ark-delete-deployment
  namespace: {{ .Values.ark.server.namespace }}
spec:
  template:
    metadata:
      name: ark-job-delete-deployment
    spec:
      containers:
        - name: hyperkube
          image: quay.io/coreos/hyperkube:v1.8.5_coreos.0
          imagePullPolicy: IfNotPresent
          command:
            - ./kubectl
            - delete
            - -f
            - /tmp/resources
          volumeMounts:
            - mountPath: "/tmp/resources"
              name: tmp-configmap-resources
      volumes:
        - name: tmp-configmap-resources
          configMap:
            name: ark-deployment
      restartPolicy: OnFailure
      serviceAccountName: ark
