apiVersion: v1
kind: Namespace
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    k8s-app: heptio-ark
  name:  {{ .Values.ark.namespace }}
