apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    k8s-app: heptio-ark
  name: ark
  namespace: {{ .Values.ark.server.namespace }}
